#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

export VERSION_SCRIPT="import sys; print('%s.%s' % sys.version_info[0:2])"
export PYTHON_VERSION=`python -c "$VERSION_SCRIPT"`

set -x

PYTHONPATH=. ${PREFIX}pytest --ignore venv -W ignore::DeprecationWarning --cov=chachacha --cov=tests --cov-fail-under=100 --cov-report=term-missing ${@}
#${PREFIX}mypy chachacha --ignore-missing-imports --disallow-untyped-defs
${PREFIX}autoflake --recursive chachacha tests setup.py
${PREFIX}black chachacha tests setup.py --check
